name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          SHA="${{ github.event.client_payload.sha }}"
          sed -i "s/v.*\.tar\.gz/v${VERSION}.tar.gz/" Formula/commit-message-cli.rb
          sed -i "s/sha256 \".*\"/sha256 \"${SHA}\"/" Formula/commit-message-cli.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update commit-message-cli to v${{ github.event.client_payload.version }}"
          title: "Update commit-message-cli to v${{ github.event.client_payload.version }}"
          branch: "update-commit-message-cli"
